### ISSUE TITLE
Suggestion to add Paradigm Protocol/Exchance

### ISSUE THREAD

**Issue by hrharder** [distribuyed/index#16]
| 	Paradigm	| 	[![alt text][web]](https://www.paradigmfoundation.io) | [![alt text][github]](https://github.com/ParadigmFoundation/Paradigm)	| [![alt text][whitepaper]](https://s3-ap-southeast-2.amazonaws.com/www.paradigmfoundation.io/Paradigm+Foundation+White+Paper.pdf) |  | 	(developing)	| 	ethereum protocol	| 	|

**Comment by eliooses** [comment]
Hi there @hrharder !

Thank you so much for this big contribution with a FULLY 😃 

I just updated:
https://github.com/distribuyed/index/commit/822b0a3ccf6dd45f375a5c1720f5b7c4a147901c

**Comment by hrharder** [comment]
Thank you for hosting this awesome list. This is an exciting project hopefully everyone will be hearing more about soon! 👍 :)

**Comment by eliooses** [comment]
I will work very soon in a html full version of this for extend and classify properly all the data.

Please, if you know another project missing in the list or an update of Paradigm, let me know. 

Best regards from Buenos Aires.
