### ISSUE TITLE
Suggestion to add Paradigm Protocol/Exchange

### ISSUE THREAD

**Issue by hrharder** [distribuyed/index#17]
|	Exchange	| URL	| REPO | Whitepaper/Docs | DEX GRADE | 	Status	| 	Protocol	| Reference |
| ------------- |:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| 	Paradigm	| 	[![alt text][web]](https://www.paradigmfoundation.io) | [![alt text][github]](https://github.com/ParadigmFoundation/Paradigm)	| [![alt text][whitepaper]](https://s3-ap-southeast-2.amazonaws.com/www.paradigmfoundation.io/Paradigm+Foundation+White+Paper.pdf) |  | 	(developing)	| 	ethereum protocol	| 	|

**Comment by eliooses** [comment]
Hi there @hrharder !

Thank you so much for this big contribution with a FULLY 😃 

I just updated:
https://github.com/distribuyed/index/commit/822b0a3ccf6dd45f375a5c1720f5b7c4a147901c
