### ISSUE TITLE
Leverj Information Update

### ISSUE THREAD

**Issue by UnfunMid** [distribuyed/index#25]
Please can you update this information under Leverj?

Whitepaper: https://leverj.io/whitepaper.pdf
Yellow Paper: https://leverj.io/LeverjProtocol.pdf
Github: https://github.com/leverj

Thanks!
Joe - Leverj Representative

**Comment by eliooses** [comment]
Hi there @UnfunMid !

Thanks a lot for your collaboration.

Yes. Of course, this night i will update.

**Comment by UnfunMid** [comment]
Much appreciated!

**Comment by eliooses** [comment]
I just update the info. Thanks for the contribution and sorry for the delay.
