### ISSUE TITLE
Adding New Dex's

### ISSUE THREAD

**Issue by IsaiahN** [distribuyed/index#28]
Accelerator ex: https://acceleratorex.com/
UberDelta: https://www.uberdelta.com/

**Comment by eliooses** [comment]
Hi there @IsaiahN !

UberDelta is OK!, but accelerator ex require of an analysis, i don´t see in what way is a DEX. 

Tomorrow I will check this out. 

Thanks a lot for your contribution. 😃

**Comment by eliooses** [comment]
Sorry for the delay. Accelerator EX will not be included. UberDelta yes.

Thanks a lot!
