### ISSUE TITLE
Add Shark Relay to the list

### ISSUE THREAD

**Issue by suchit-gupta** [distribuyed/index#35]
Exchange: Shark Relay
URL: https://app.sharkrelay.com
REPO: N/A
Whitepaper: N/A
DEX Grade: ACL/ DCD
Status: (developing - Live)
Protocol: 0x protocol

I have tried pull request before....can you add this? Thanks in advance!

**Comment by eliooses** [comment]
Hi there @suchit-gupta !

Sorry for the delay. Shark Relay was added. Thanks a lot for your contribution.
