### ISSUE TITLE
Add DEXTRACKER

### ISSUE THREAD

**Issue by nsexer** [distribuyed/index#41]
https://etherscan.io/stat/dextracker

PS: Thanks for quoting my article!

**Comment by eliooses** [comment]
Hi @nsexer !, thanks to you for your brilliant article. I quoted too in my Medium post: https://medium.com/@oseselio/index-a-comprehensive-list-of-decentralized-exchanges-cf4985c79d7e

Please, if you write again about DEX, let me know directly: elio@netfilmx.com

I just added Etherscan DEX Tracker and DEX Order book to the list:
https://github.com/distribuyed/index/commit/3846dd9b4bea009a70f5e169c24fbf16cabef35b

Thanks for your contribution.
