### ISSUE TITLE
Add swap.online

### ISSUE THREAD

**Issue by caffeinum** [distribuyed/index#50]
swap.online is an atomic-swap based DEX. Runs fully in browser! repos are at: https://github.com/swaponline

**Comment by caffeinum** [comment]
- [x] Accountless: The project should be accesible without registration, KYC or AML policies. ACL
- [x] Decentralized Capital Deposits (self-custodied): You should be able to trade directly out of your own wallet. DCD
- [x] Decentralized Client: The trades should be possibles through a downloadable client or build it from source. DC
- [x] Decentralized Development: The project should be open source. DD
- [ ] Decentralized DNS: The project should be accessible through a decentralized domain name service (like ENS). **That's easily addable though** DDNS
- [ ] Decentralized Governance: The direction of the project should be governed by the project's service providers. DG
- [x] Decentralized Order Books: Orderbooks should be synced among various parties to prevent any malicious behavior in a similar way that blockchain validation consensus is decentralized. DOB
- [ ] Decentralized Order Matching: **It's manual currently**
- [x] Decentralized Swap: The usage of atomic swaps. The trader's funds should go directly from one to the other without any other parties handling the funds. DS
- [x] Decentralized Settlement: DSTT
- [x] Fully Decentralized: FULLY
- [x] Open Protocol: OPRO
- [ ] Relayer: RELAY **not sure**

**Comment by eliooses** [comment]
Hi there!, thanks a lot @caffeinum for the contribution and deeply apologies for the delay.

I just added Swap.Online. Please check the updates and let me know if is fine for you.

Best regards from Buenos Aires.

**Comment by caffeinum** [comment]
@eliooses thanks!
